services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: nolock-test-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NoLock_Test123!"
    ports:
      - "11433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "NoLock_Test123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
